# Generated by Django 5.2 on 2025-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('incident_type', models.CharField(choices=[('fire', 'Fire'), ('ems', 'EMS'), ('traffic', 'Traffic'), ('crime', 'Crime'), ('natural', 'Natural')], max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
